# src/sdz/BlogBundle/Resources/config/routing.yml

sdzblog_accueil:
    path:      /{page}
    defaults:  { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements:
        page: \d*
    
sdzblog_ajouter:
    path:      /ajouter
    defaults:  { _controller: SdzBlogBundle:Blog:ajouter }
    
sdzblog_voir:
    path:     /article/{id}
    defaults: { _controller: SdzBlogBundle:Blog:voir }
    requirements:
        id: \d+
            
sdzblog_modifier:
    path:     /modifier/{id}
    defaults: { _controller: SdzBlogBundle:Blog:modifier }
    requirements:
        id: \d+

sdzblog_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: SdzBlogBundle:Blog:supprimer }
    requirements:
        id: \d+